name: ttgt
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  firebase_core: ^1.1.0
  firebase_database: ^6.0.0
  get: ^4.1.4
  flutter_staggered_animations: "^1.0.0"
  http: ^0.13.3
  webview_flutter: ^2.0.4
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/

